runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  API_KEY: AIzaSyB0hwTmrm40K-kxao32kSDnzmH_UWnL8eI

handlers:

  - url: /
    static_files: dist/dental-app/index.html
    upload: dist/dental-app/index.html
  - url: /
    static_dir: dist/dental-app

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE