steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm:node-10.10.0'
    args: [ 'install' ]

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm:node-10.10.0'
    args: [ 'run', 'build', '--prod' ]

  # Deploy to google cloud app egnine
  - name: 'gcr.io/dentalappmanagement/firebase'
    args: [ 'deploy', '-P', 'js-demo-fe-staging', '--token', 'AIzaSyB0hwTmrm40K-kxao32kSDnzmH_UWnL8eI']
